# Generated by Django 5.2.11 on 2026-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
