# Generated by Django 5.2.11 on 2026-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(max_length=1000)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sizes', models.JSONField(default=list)),
                ('fit', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular')], max_length=50)),
                ('fabric', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
